version: '3'

services:
  mqtt_broker:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mqtt
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf


  